# Generated by Django 5.2.15 on 2026-06-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_employerprofile_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='bot_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('intake', 'Intake'), ('negotiating', 'Negotiating'), ('working', 'Working')], default='idle', max_length=20),
        ),
    ]
