# Generated by Django 5.2.15 on 2026-06-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_workerprofile_bot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='bot_state',
            field=models.CharField(choices=[('menu', 'Menu'), ('intake', 'Intake'), ('negotiating', 'Negotiating'), ('working', 'Working')], default='menu', max_length=20),
        ),
    ]
