# Generated by Django 5.2.15 on 2026-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_workerprofile_bot_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='toli_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='bot_state',
            field=models.CharField(choices=[('menu', 'Menu'), ('intake', 'Intake'), ('toli_preference', 'Toli Preference'), ('distance_preference', 'Distance Preference'), ('job_selection', 'Job Selection'), ('negotiating', 'Negotiating'), ('working', 'Working')], default='menu', max_length=25),
        ),
    ]
