# Generated by Django 5.2.15 on 2026-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_workerprofile_bot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='bot_state',
            field=models.CharField(choices=[('language_selection', 'Language Selection'), ('menu', 'Menu'), ('intake', 'Intake'), ('toli_preference', 'Toli Preference'), ('distance_preference', 'Distance Preference'), ('job_selection', 'Job Selection'), ('negotiating', 'Negotiating'), ('working', 'Working')], default='language_selection', max_length=50),
        ),
    ]
